[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.31"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

remappings = [
    "@luxfi/=lib/standard/contracts/",
    "@luxfi/standard/=lib/standard/contracts/",
    "@openzeppelin/contracts/=lib/standard/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/standard/lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.31"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"
verbosity = 2
fuzz = { runs = 256 }
remappings = [
    "@luxfi/=lib/standard/contracts/",
    "@luxfi/standard/=lib/standard/contracts/",
    "@openzeppelin/contracts/=lib/standard/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/standard/lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "preserve"

[rpc_endpoints]
hanzo_mainnet = "http://127.0.0.1:19630/ext/bc/2MqjR3NQTSCTmMRirA7NpHsv2nsgNDCrzdhb1Pt15xbb8CHQRF/rpc"
hanzo_testnet = "http://127.0.0.1:19640/ext/bc/uRzy7Z9drJxuVdCKkdqj6ZTCYcx1hLJpuaGFHG4MdUcYWDa8b/rpc"
hanzo_devnet = "http://127.0.0.1:19650/ext/bc/8saqkhsUrijPci3RXQnNaaLLkYXBErauhwUsZZwdj8erxeaZv/rpc"

[doc]
out = "docs"
repository = "https://github.com/hanzoai/hanzo"
